on:
  push:
    branches:
      - v2.0.10
  pull_request:
    branches:
      - v2.0.10
jobs:
  release-windows:
    runs-on: windows-latest

#    strategy:
#      matrix:
#        os:

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          BRANCH: v2.0.10
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          build_script_name: packElectron:win --publish always

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

#  release-mac:
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      matrix:
#        os: macos-latest
#
#    steps:
#      - name: Check out Git repository
#        uses: actions/checkout@v1
#
#      - name: Install Node.js, NPM and Yarn
#        uses: actions/setup-node@v1
#        with:
#          node-version: 10
#
#      - name: Build/release Electron app
#        uses: samuelmeuli/action-electron-builder@v1
#        env:
#          BRANCH: v2.0.10
#        with:
#          # GitHub token, automatically provided to the action
#          # (No need to define this secret in the repo settings)
#          github_token: ${{ secrets.github_token }}
#          build_script_name: packElectron:mac
#
#          # If the commit is tagged with a version (e.g. "v1.0.0"),
#          # release the app after building
#          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
